# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);


GET http://localhost:3000/health
###

GET http://localhost:3000/generateCustomerId
###

GET http://localhost:3000/assets?id=10
###


POST http://localhost:3000/assets
Content-Type: application/json

{
  "customer": {
    "name": "Mike Mueller",
    "zip": "3003",
    "points": 0,
    "location": "Bern",
    "address": "Hilfikerstrasse 1",
    "id": 10,
      "assets": [
          {
              "status": true,
              "gpio": 18,
              "times": [
                  {
                      "endTime": "NULL",
                      "startTime": "NULL",
                      "minDuration": "NULL"
                  }
              ],
              "id": 11,
              "name": "Freezer"
          },
          {
              "status": true,
              "gpio": 23,
              "times": [
                  {
                      "endTime": "NULL",
                      "startTime": "NULL",
                      "minDuration": "NULL"
                  }
              ],
              "id": 12,
              "name": "Charging Station"
          }
      ]
  }

}
###


PUT http://localhost:3000/assets?id=10
Content-Type: application/json

{
  "customer": {
    "name": "Mike Mueller",
    "zip": "3003",
    "points": 28,
    "location": "Bern",
    "address": "Hilfikerstrasse 1",
    "id": 10,
      "assets": [
          {
              "status": true,
              "gpio": 18,
              "times": [
                  {
                      "endTime": "NULL",
                      "startTime": "NULL",
                      "minDuration": "NULL"
                  }
              ],
              "id": 11,
              "name": "Freezer"
          },
          {
              "status": true,
              "gpio": 23,
              "times": [
                  {
                      "endTime": "NULL",
                      "startTime": "NULL",
                      "minDuration": "NULL"
                  }
              ],
              "id": 12,
              "name": "Charging Station"
          }
      ]
  }
}

###
